title: "Marshallese Community in Utah"
description: "Stories, events, news, and resources for the Marshallese community in Utah."
theme: 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Navigation links
header_pages:
- about.md
- resources.md
- contact.md
